import type { Metadata } from "next";
import React from "react";
import Header from "@/app/components/Header";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import "nes.css/css/nes.min.css";

const pressStart2P = Press_Start_2P({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={pressStart2P.className}
      >
        <main className="h-[100vh]">
          <Header />
          {children}
          <Footer/>
        </main>
        
      </body>

    </html>
  );
}
